export { default as About } from "./About"
export { default as Hero } from "./Hero"
export { default as Contact } from "./Contact"
export { default as Experience } from "./Experience"
export { default as Work } from "./Work"
export { default as Navbar } from "./Navbar"
export { default as SocialLinks } from "./SocialLinks"
export { default as Footer} from "./Footer"